language: node_js
install: npm install --no-optional
git:
  depth: 1
node_js:
- 10
- 9
- 8
- 7
- 6
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: coverage
    install: npm install istanbul coveralls
    script: npm run coverage
    after_success: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: npm
      email: ivo.putzer@gmail.com
      api_key: $NPM_TOKEN
      on:
        branch: master
        repo: $TRAVIS_REPO_SLUG
    after_deploy:
    - npm view
  allow_failures:
  - node_js: 7
  - node_js: 6
